USE {DATABASE_PLACEHOLDER};

ALTER TABLE movies DISABLE KEYS;

SET GLOBAL local_infile=true;

LOAD DATA LOCAL INFILE "{PATH_PLACEHOLDER}"
INTO TABLE movies
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(movieId, title, genres)
SET year = CAST(SUBSTR(REGEXP_SUBSTR(title, '[(][0-9]{4}[)]$'),2,4) AS UNSIGNED INT),
title = IF (title REGEXP('\([0-9]{4}\)'), SUBSTR(title,1,LENGTH(title)-7), title);

ALTER TABLE movies ENABLE KEYS;
