USE {DATABASE_PLACEHOLDER};

ALTER TABLE ratings DISABLE KEYS;

SET GLOBAL local_infile=true;

LOAD DATA LOCAL INFILE "{PATH_PLACEHOLDER}"
INTO TABLE ratings
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(userid, movieid, rating, @pass);

ALTER TABLE ratings ENABLE KEYS;
